/** Task, Message, Artifact, and Part data models — A2A compatible. */

import {
  TaskCanceledError,
  TaskFailedError,
  TaskRejectedError,
  TaskTimeoutError,
} from "./exceptions.js";

/** A2A task lifecycle states. */
export enum TaskStatus {
  SUBMITTED = "submitted",
  WORKING = "working",
  INPUT_REQUIRED = "input_required",
  COMPLETED = "completed",
  FAILED = "failed",
  CANCELED = "canceled",
  REJECTED = "rejected",
}

/** Returns true if the status is terminal (no further updates expected). */
export function isTerminal(status: TaskStatus): boolean {
  return [
    TaskStatus.COMPLETED,
    TaskStatus.FAILED,
    TaskStatus.CANCELED,
    TaskStatus.REJECTED,
  ].includes(status);
}

/** The smallest content unit in a message or artifact. */
export interface Part {
  text?: string;
  data?: Record<string, unknown>;
  url?: string;
  raw?: Uint8Array;
  mediaType?: string;
  metadata?: Record<string, string>;
}

/** A communication turn between agents. */
export interface Message {
  role: "user" | "agent";
  parts: Part[];
  messageId?: string;
}

/** A concrete output generated by an agent. */
export interface Artifact {
  artifactId?: string;
  name?: string;
  parts: Part[];
}

/** Represents a complete A2A task with all state. */
export interface Task {
  taskId: string;
  contextId?: string;
  status: TaskStatus;
  messages: Message[];
  artifacts: Artifact[];
  targetSkillId?: string;
  originatorPeerId?: string;
}

/** Handle for tracking a remote task's progress. */
export class TaskHandle {
  private _task: Task;
  private readonly _cancelFn: () => Promise<void>;
  private _resolve?: () => void;
  private _donePromise: Promise<void>;

  constructor(task: Task, cancelFn: () => Promise<void>) {
    this._task = task;
    this._cancelFn = cancelFn;
    this._donePromise = new Promise<void>((resolve) => {
      this._resolve = resolve;
    });
    if (isTerminal(task.status)) {
      this._resolve?.();
    }
  }

  get taskId(): string {
    return this._task.taskId;
  }
  get status(): TaskStatus {
    return this._task.status;
  }
  get artifacts(): Artifact[] {
    return this._task.artifacts;
  }

  /** Called internally when a status update is received from the daemon. */
  _update(status: TaskStatus, artifacts?: Artifact[]): void {
    this._task.status = status;
    if (artifacts) this._task.artifacts = artifacts;
    if (isTerminal(status)) this._resolve?.();
  }

  /**
   * Wait for the task to reach a terminal state.
   * @param timeoutMs Maximum milliseconds to wait. Undefined means wait forever.
   */
  async wait(timeoutMs?: number): Promise<Task> {
    if (timeoutMs !== undefined) {
      const timer = new Promise<never>((_, reject) => {
        setTimeout(
          () => reject(new TaskTimeoutError(`Task ${this.taskId} timed out after ${timeoutMs}ms`)),
          timeoutMs,
        );
      });
      await Promise.race([this._donePromise, timer]);
    } else {
      await this._donePromise;
    }

    if (this._task.status === TaskStatus.FAILED) {
      throw new TaskFailedError(`Task ${this.taskId} failed`);
    }
    if (this._task.status === TaskStatus.CANCELED) {
      throw new TaskCanceledError(`Task ${this.taskId} was canceled`);
    }
    if (this._task.status === TaskStatus.REJECTED) {
      throw new TaskRejectedError(`Task ${this.taskId} was rejected`);
    }
    return this._task;
  }

  /** Request cancellation of this task. */
  async cancel(): Promise<void> {
    await this._cancelFn();
  }
}

/** A task received from a remote agent for local processing. */
export interface IncomingTask {
  taskId: string;
  peerId: string;
  messages: Message[];
  targetSkillId: string;
  senderCard?: Record<string, unknown>;
  updateStatus: (status: string) => Promise<void>;
  complete: (artifacts?: Artifact[]) => Promise<void>;
  fail: (error: string) => Promise<void>;
  requestInput: (message?: Message) => Promise<void>;
}
